microsoft/com-rs

examples/basic/client/src/main.rs, src/interfaces/iunknown.rs
Just a couple of typos - although the whole trait doesn't exist anyway, so not sure how important these are. The only `get_interface` I saw implemented was on [`InterfaceRc`](https://github.com/microsoft/com-rs/blob/99112fc5a1661bb290a1f69b899ce5b046f40e70/src/interface_rc.rs#L37-L52).
=> Fix IUknown typos in documentation

Cargo.toml
The CI was running `cargo test` and `cargo fmt` in the root, but since the root wasn't a cargo workspace, this did nothing to the other crates (macros and macros/support).
Adding a `[workspace]` section in the `Cargo.toml` should inform cargo of these other crates and make things better in CI.
(I'm not _entirely_ sure whether this has some unwanted side effects, so I'm curious to see what the CI has to say about it.)
=> Run macros and macros/support tests/fmt in CI

macros/src/lib.rs, macros/support/src/co_class/com_struct_impl.rs, macros/support/src/com_interface/com_interface_impl.rs, macros/support/src/com_interface/vtable.rs, macros/support/src/utils/idents.rs
Before:
```
error: custom attribute panicked
--> $DIR/generic_coclass.rs:3:1
|
3 | #[com_interface]
| ^^^^^^^^^^^^^^^^
|
= help: message: called `Option::unwrap()` on a `None` value
```
After:
```
error: custom attribute panicked
--> $DIR/generic_coclass.rs:3:1
|
3 | #[crate::com_interface]
| ^^^^^^^^^^^^^^^^^^^^^^^
|
= help: message: Supertrait path isn't an ident
```
Was playing with generic `co_class`es and getting nothing but `Option::unwrap() on None` was getting a bit annoying to debug. This should make things easier in that respect. :)
There were couple of `unwrap`s that shouldn't ever be triggered because the requirements were checked just few lines before. I opted to replace these with `expect` just in case the code changes in the future and it was more of a no brainer to use …
=> Replace unwraps with expect

macros/support/src/com_interface/com_interface_impl.rs, macros/support/src/com_interface/vtable.rs, macros/support/src/com_interface/vtable_macro.rs, macros/tests/progress.rs, macros/tests/supertrait_path.rs
Instead of having to `use` the `IUnknown` everywhere, this PR adds support for:
```rust
#[com_interface(...)]
trait Foo: com::interfaces::iunknown::IUnknown {}
```
Most of the bits were very straight forward. The one places where the implementation got a bit complex (and a bit fragile) is the `#[derive(VTable)]` expansion, which used to derive the interface ident from the field name (making assumptions such as all interfaces starting with `I`) - the new implementation assumes the type is defined as an associated type of the original interface:
```rust
<dyn path::to::some::Interface as ...>::VTable
// ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use this
```
This branch is in a conflict with #108 and will fail to build with #107. I'll merge things around once I have a better idea what PRs will land and …
=> Support paths when defining supertrait for [com_interface]

README.md, examples/aggregation/interface/src/ifile_manager.rs, examples/aggregation/interface/src/ilocal_file_manager.rs, examples/basic/interface/src/ianimal.rs, examples/basic/interface/src/icat.rs, examples/basic/interface/src/icat_class.rs, examples/basic/interface/src/idomesticanimal.rs, examples/basic/interface/src/iexample.rs, macros/support/src/com_interface/iid.rs, macros/tests/no_supertrait.rs, macros/tests/no_supertrait.stderr, macros/tests/non_string_guid.rs, macros/tests/non_string_guid.stderr, macros/tests/progress.rs, macros/tests/supertrait_path.rs, src/interfaces/iclass_factory.rs, src/interfaces/iunknown.rs
Define the GUID as a string in the `#[com_interface("<iid>")]` attributes.
Needed something easy and simple to work on. :)
Closes #90
=> Define [com_interface] IID as string

README.md
=> Fix unclosed parentheses in README.md

docs/safety.md, examples/aggregation/client/src/main.rs, examples/aggregation/interface/src/ifile_manager.rs, examples/aggregation/interface/src/ilocal_file_manager.rs, examples/aggregation/server/src/local_file_manager.rs, examples/aggregation/server/src/windows_file_manager.rs, examples/basic/client/src/main.rs, examples/basic/interface/src/ianimal.rs, examples/basic/interface/src/icat.rs, examples/basic/interface/src/idomesticanimal.rs, examples/basic/server/src/british_short_hair_cat.rs, macros/support/src/aggr_co_class/iunknown_impl.rs, macros/support/src/co_class/class_factory.rs, macros/support/src/co_class/iunknown_impl.rs, macros/support/src/co_class/mod.rs, macros/support/src/com_interface/interface_impl.rs, macros/support/src/com_interface/vtable.rs, src/inproc.rs, src/interface_rc.rs, src/interfaces/iclass_factory.rs, src/interfaces/iunknown.rs
As a partial solution to #97. 
Hopefully the new docs add some explanation as to why. This requires all COM interface methods to be marked `unsafe`. The short and sweet reason for this is that it is always possible that a COM interface implementation can do something that will violate Rust's safety rules but still be a valid COM interface. Because of this, we require the caller of every COM interface method to verify that calling the method does not violate Rust's safety rules.
=> Require `unsafe`

src/interface_ptr.rs, src/interface_rc.rs, src/interfaces/mod.rs
This addresses most of the issues in #99. 
`InterfacePtr` should only be constructed if `AddRef` was called on the underlying interface before the raw pointer is moved into `InterfacePtr::new`. The documentation of `InterfacePtr::new` now reflects this. It is up to the user to ensure that `Release` gets called when that `InterfacePtr` is no longer needed. This is usually done by converting `InterfacePtr` to an `InterfaceRc` through the `InterfacePtr::upgrade` method. 
These changes make it possible to leak memory but not to violate safety rules unless some invariant is not held when calling an `unsafe` function. 
Clone on `InterfacePtr` now correctly calls `add_ref` to ensure that the invariant of `AddRef` being called before `InterfacePtr::new` is constructed is upheld.
=> Improve the two Interface pointers

src/lib.rs, src/offset.rs
I did not know how else to fix this, so user can have any amount of implemented interfaces, so I atleast raised it to five.
Fixes #134
=> Allow users to implement five five interfaces instead of three

CHANGELOG.md
This fixes markdown links in `CHANGELOG.md` file.
Thanks!
=> Fix markdown links

src/ptr.rs
=> Fix a typo in the documentation.

.github/workflows/ci-workflow.yml, examples/basic/client/src/main.rs, examples/basic/server/src/british_short_hair_cat.rs, macros/support/src/class/class.rs, macros/support/src/class/class_constructor.rs, macros/support/src/class/class_factory.rs, macros/support/src/class/iunknown_impl.rs, macros/support/src/interface/interface.rs, src/production.rs, src/production/class.rs, src/production/registration.rs
Fixes #161 
This (hopefully) fixes the issues in #161 which are:
* **COM interface methods must be called on objects that are heap allocated**: We don't force the user to conform to this for regular methods because it's possible to safely use methods with `&self`. However, the IUnknown methods assume that self is heap allocated and won't move. We model this by taking self as `self: &Pin<Box<Self>>`. This makes it not possible to call IUnknown methods on a stack allocated object. If users must assume that their code is heap allocated they can declare their methods with the same signature as the IUnknown methods but if the assumption is not needed, they can just use `&self`. 
* **There is no safe query_interface**: classes now come with a safe query interface method called `query`. This may …
=> Allocated Classes

README.md, docs/basic-usage.md, docs/safety.md, examples/basic/client/src/main.rs, examples/basic/interface/src/ianimal.rs, examples/basic/interface/src/icat.rs, examples/basic/interface/src/idomesticanimal.rs, examples/basic/server/src/british_short_hair_cat.rs, examples/d2d-clock/src/main.rs, macros/support/src/class/class.rs, macros/support/src/class/class_factory.rs, macros/support/src/class/iunknown_impl.rs, macros/support/src/interface/interface.rs, src/interfaces/iclass_factory.rs, src/interfaces/iunknown.rs, src/production/registration.rs
This fixes the concern that @kennykerr had where safe versions of COM methods had different names (to avoid name conflicts). This change makes raw COM methods use CamelCasing (e.g., `QueryInterface`) while safe versions use the more idiomatic camel_case style (e.g., `query_interface`).
=> Switch casing for raw COM methods to CamelCase and add some docs

Cargo.toml, src/lib.rs
Currently both the reexported production module and class macro do not appear on docs.rs because they are gated behind a feature cfg. Enabling all features when compiling for docs.rs should make them show up again.
---
I've not been able to properly test this as `cargo doc --open` doesn't seem to take `package.metadata.docs.rs` into account, and I can't find if there's a special flag to make it do such a build.
=> Enable all features when compiling for docs.rs

macros/support/src/class/class_factory.rs, tests/ui/pass/class_fields.rs
Having multiple fields in a class does not compile. This change makes the code below compile as expected.
```
com::class! {
pub class BritishShortHairCat: IAnimal {
hello: u32,
hi: u32
}
[...]
}
```
Fixes #186
=> fix com::class! class with multiple fields

src/production/registration.rs
CLSIDs have to be enclosed in braces. Fixes #189.
=> Fix incorrect CLSID registry keys

Cargo.toml, docs/safety.md, examples/lib_no_std/Cargo.toml, examples/lib_no_std/src/lib.rs, macros/support/src/class/class.rs, macros/support/src/class/class_constructor.rs, macros/support/src/class/class_factory.rs, macros/support/src/class/iunknown_impl.rs, macros/support/src/interface/interface.rs, macros/support/src/interface/mod.rs, macros/support/src/interface/vptr.rs, macros/support/src/interface/vtable.rs, src/abi_transferable.rs, src/interface.rs, src/interfaces/iclass_factory.rs, src/interfaces/iunknown.rs, src/lib.rs, src/production/class.rs, src/production/registration.rs, src/runtime.rs, src/sys.rs
This changes the generated code so that it uses the core crate
(where applicable) instead of the std crate. Almost everything in the
generated code can directly use core, with the only exceptions being
allocation container types, like Box. These are changed to use
`alloc::boxed::Box`.
This allows the generated code to work in crates that are using
`#![no_std]`. I've also added a very simple example crate that
demonstrates using `com-rs` with `#![no_std]`.
Also, I edited the doc comments for `IUnknown::AddRef` and
`IUnknown::Release`. They contained references to a ComPtr type, which
no longer exists.
=> Support for no_std environments

docs/safety.md, macros/support/src/class/class.rs, macros/support/src/class/iunknown_impl.rs, macros/support/src/interface/vtable.rs, src/interface.rs, src/production/registration.rs
This allows com-rs to compile on non-Windows platforms. Specifically,
when compiling on aarch64-linux-android, Rust rejects this because
the "stdcall" calling convention is unsupported.  The "system" calling
convention is an alias for "stdcall" on Windows, and is just "use the
normal calling convention" on all other platforms.
=> Use extern "system" instead of extern "stdcall"

.gitignore, src/abi_transferable.rs
This commit adds usize to primitive_transferable_type macro
so that it is AbiTransferable. There are a number of pointer types
that are aliases of usize, since their size is dependent on
processor word size e.g. UINT_PTR.
=> Add usize as AbiTransferable

.github/workflows/ci-workflow.yml
CI pipelines are failing because an indirect dependency has
increased its minimum supported Rust version, due to using `if`
inside `const fn`. Cargo currently has no way to make crate version
selections dependent on compiler version, so we are forced to raise
the minimum required version for `com-rs`.
=> Increase minimum supported version to 1.46.0

macros/support/src/interface/interface.rs, tests/ui/pass/interface_eq.rs
Pointer equality is meaningful for COM interfaces, and is often used
in COM code bases. This adds `#[derive(PartialEq, Eq)]` for generated
COM interfaces. It includes a compile test.
=> Implement Eq and PartialEq for COM interfaces

macros/support/src/class/class.rs, tests/ui/pass/multiversion.rs
Resolve name collisions among methods defined on different interfaces, by
renaming some methods with a disambiguating suffix.
It is common for designers of COM interfaces to define multiple versions of
the same interface, where each new interface is a superset of the previous
version. For examples, see these DirectWrite interfaces:
* [IDWriteTextFormat](https://docs.microsoft.com/en-us/windows/win32/api/dwrite/nn-dwrite-idwritetextformat)
* [IDWriteTextFormat1](https://docs.microsoft.com/en-us/windows/win32/api/dwrite_2/nn-dwrite_2-idwritetextformat1)
* [IDWriteTextFormat2](https://docs.microsoft.com/en-us/windows/win32/api/dwrite_3/nn-dwrite_3-idwritetextformat2)
* [IDWriteTextFormat3](https://docs.microsoft.com/en-us/windows/win32/api/dwrite_3/nn-dwrite_3-idwritetextformat3)
These …
=> Handle COM interfaces with colliding method names

macros/support/src/interface/iid.rs, macros/support/src/interface/vptr.rs, macros/support/src/interface/vtable.rs
This adds `#[doc(hidden)]` to several generated items: the vtable
statics for classes, the IID for interfaces, and a type alias.
This makes `cargo doc` a lot cleaner.
=> Hide some implementation details from docs

macros/support/src/class/class.rs
Overlooked style nit from https://github.com/microsoft/com-rs/pull/224/files#r732498255 that both makes the code more pretty to read as per the suggestion from @rylev, _and_ by using the boolean result from `.insert()` no second lookup with `.contains()` needs to be performed, shaving some cylces off.
---
Test: `cargo t --all` remains successful with this.  Commenting out the `.filter()` line makes some tests fail.
CC @sivadeilra
=> macros/class: Fix HashSet contains+inserts pair to only lookup once

src/abi_transferable.rs
The `set_abi` trait method is defined, but never used. I'm guessing this is a leftover from some previous design.
=> Remove `set_abi` from `AbiTransferable`
